#!/bin/bash

var PROJECTS $HOME/projects
var TERMINAL_APPS $TERMINAL/apps

import "$TERMINAL_APPS/taskwarrior"
import "$TERMINAL_APPS/android"
import "$TERMINAL_APPS/docs"
import "$TERMINAL_APPS/backup"
import "$TERMINAL_APPS/analytics"
import "$TERMINAL_APPS/calculator"
import "$TERMINAL_APPS/hubstaff"
import "$TERMINAL_APPS/tmux"
import "$TERMINAL_APPS/games"
import "$TERMINAL_APPS/kde"
import "$TERMINAL_APPS/git-completion"
import "$TERMINAL_APPS/git-shortcuts"
import "$TERMINAL_APPS/npm-completion"
import "$TERMINAL_APPS/3dprint"
import "$TERMINAL_APPS/git-tools"
import "$TERMINAL_APPS/youtube"
import "$TERMINAL_APPS/aws"
import "$TERMINAL_APPS/dotnet"
import "$TERMINAL_APPS/audio-feedback"
import "$TERMINAL_APPS/rust"
import "$TERMINAL_APPS/jetbrains"
import "$TERMINAL_APPS/gum"
import "$TERMINAL_APPS/deno"
import "$TERMINAL_APPS/docker"
import "$TERMINAL_APPS/vim"
import "$TERMINAL_APPS/zoxide.sh"
import "$TERMINAL_APPS/openapi"
import "$TERMINAL_APPS/tailwind"
# import "$TERMINAL_APPS/guitar"
